from fastapi import FastAPI
from functools import lru_cache
from app.routes import general, map, graph
from . import config

app = FastAPI(
    title="AtmoSwing Web Forecast API",
    description="API to provide forecasts generated by AtmoSwing.",
    version="1.0.0",
)

@lru_cache
def get_settings():
    return config.Settings()

# Include the routes
app.include_router(general.router, prefix="/general", tags=["General Data"])
app.include_router(map.router, prefix="/map", tags=["Map Data"])
app.include_router(graph.router, prefix="/graph", tags=["Graph Data"])
